services:
  db-mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    container_name: db_mongo
    environment:
      - MONGO_USER=mongodbuser
      - MONGO_PASSWORD=mongodbpassword
    restart: always
