services:
  db-mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    container_name: db_mongo
    environment:
      - MONGO_USER=mongodbuser
      - MONGO_PASSWORD=mongodbpassword
    restart: always

  db-mongo-test:
    image: mongo:latest
    ports:
      - '27018:27017'
    container_name: db_mongo_test
    environment:
      - MONGO_USER=dbmongotest
      - MONGO_PASSWORD=mongodbpassword
    restart: always